services:
  redis:
    image: "redis:8-alpine"
    container_name: "redis-book-talker"
    ports:
      - "6379:6379"
    command:
      - "redis-server"
#    volumes:
#      - redis_volume_data:/data

  postgresql:
    image: "postgres:13.10-alpine"
    container_name: "postgresql-book-talker"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "book_talker_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"