spring:
  profiles:
    active: local

  application:
    name: book_talker_backend

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        order_inserts: true

server:
  port: 8010
  forward-headers-strategy: native

management:
  endpoints:
    web:
      exposure:
        include: health
