spring:
  application:
    name: book_talker_backend

  session:
    redis:
      namespace: book_talker:session

  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
      # TODO: 후에 전략 수정

  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/book_talker_db

  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          naver:
            client-name: Naver
            client-id: gP9iCmsiOkKQNSlQRkqt
            client-secret: VhPBrEXpPt
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8010/login/oauth2/code/naver
            scope:
            - id
            - name
            - email
            - gender
            - age
            - birthday
            - profile_image
            - birthyear
            - mobile

server:
  port: 8010

logging:
  level:
    root: info
