spring:
  application:
    name: book_talker_backend

  session:
    redis:
      namespace: book_talker:session

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8010

logging:
  level:
    root: debug
