spring:
  profiles:
    active: local

  application:
    name: book_talker_backend

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        order_inserts: true

server:
  port: 8010
  forward-headers-strategy: native

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
        http.client.requests: 0.5, 0.95, 0.99
